### ISSUE TITLE
Export `replaceSlots` function?

### ISSUE THREAD

**Issue by danielinteractive** [Bioconductor/BiocGenerics#11]
Hi,

I see that `BiocGenerics:::replaceSlots` is used and recommended in some places, e.g. https://www.bioconductor.org/packages/devel/bioc/vignettes/SummarizedExperiment/inst/doc/Extensions.html#37_Enabling_subsetting_operations

Now as we unfortunately know `R CMD check` does not really like using the `:::` trick to get unexported functions from packages. And I also don't really like copying the code into our package just to circumvent this (plus possible license issues).

How about just exporting `replaceSlots`?

Thanks for considering.
Cheers
Daniel

**Comment by nturaga** [comment]
Hi, please take a look at the package `Bioconductor/BiocUtils`. That will address this issue.
