### ISSUE TITLE
`%in%` conflict

### ISSUE THREAD

**Issue by bschilder** [Bioconductor/BiocGenerics#12]
Hello, 

I noticed an issue arises when trying to subset a `GRanges` object after `BiocGenerics` is attached (in this case by `regioneR::getGenome`).

## Reprex1

The following produces an error when running it from within a one of [my package's functions](https://github.com/RajLabMSSM/echoannot/blob/46d40ce5f5a108e2ef0dd1231dab6dbc888c3474/R/import_bedgraph_chroms.R) (but, oddly, not when I run it line-by-line):

```R
if(!require("regioneR")) BiocManager::install("regioneR")

func <- function(chroms =  c("chr6", "chr8")){  

        all_chrom <- regioneR::getGenome(genome ="hg19")
        
        select_chrom <- all_chrom[GenomicRanges::seqnames(all_chrom) %in% chroms, ]
        return(select_chrom)
 }
func()
```

### Error

```
error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments
```

### Full console output

Here is the full console output when running from within my R package. 
You can see that the error occurs right after `BiocGenerics` gets attached.

```
Querying 1 samples.

Query: GSM4703766 
Using build: hg19
Determining available file types.
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
1 supplementary file(s) found: 
 - GSM4703766_GAWSU510-A549-H3K4me3-ChIP-rep2_AGTCAA_GAWSU510_CKDL200157349-1a-13_HC3LFBBXX_L2_PE_R1-2.fastq.sam_noDup_RPBM.bedgraph.gz
Computing peaks from bedGraph file.
Importing chromosomes: chr6
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories'
for details

replacement repositories:
    CRAN: https://cran.rstudio.com/


Attaching package: 'BiocGenerics'

The following objects are masked from 'package:stats':

    IQR, mad, sd, var, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname,
    do.call, duplicated, eval, evalq, Filter, Find, get, grep, grepl,
    intersect, is.unsorted, lapply, Map, mapply, match, mget, order, paste,
    pmax, pmax.int, pmin, pmin.int, Position, rank, rbind, Reduce, rownames,
    sapply, setdiff, sort, table, tapply, union, unique, unsplit, which.max,
    which.min


Attaching package: 'S4Vectors'

The following objects are masked from 'package:base':

    expand.grid, I, unname


Attaching package: 'Biostrings'

The following object is masked from 'package:base':

    strsplit

The masked version of 'hg19' is not installed. Using the unmasked version. This means that no automatic masking will be available.
+ Selecting available chromosomes.
error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector argumentsSaving results ==>  /var/folders/zq/h7mtybc533b1qzkys_ttgpth0000gn/T//RtmpdxqwBu/file832c2b34218grl.hg38.rds
```

## Potential source

I think this might have something to do with different behaviours between `S4Vectors::%in%` and `BiocGenerics::%in%`

## Temporary solution

Using `grepl `instead of `%in%` seems to work ok, both within and outside of my package function.

```R 
select_chrom <-  all_chrom[grepl(paste(paste0("^",chroms,"$"),collapse = "|"),
                        as.character(GenomicRanges::seqnames(all_chrom))), ]
```

Best, 
Brian

## Session info 

<details>

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] regioneR_1.26.1                   BSgenome.Hsapiens.UCSC.hg19_1.4.3
 [3] BSgenome_1.62.0                   rtracklayer_1.54.0               
 [5] Biostrings_2.62.0                 XVector_0.34.0                   
 [7] GenomicRanges_1.46.1              GenomeInfoDb_1.30.1              
 [9] IRanges_2.28.0                    S4Vectors_0.32.4                 
[11] BiocGenerics_0.40.0              

loaded via a namespace (and not attached):
  [1] utf8_1.2.2                    reticulate_1.24-9000         
  [3] R.utils_2.11.0                tidyselect_1.1.2             
  [5] RSQLite_2.2.11                AnnotationDbi_1.56.2         
  [7] htmlwidgets_1.5.4             grid_4.1.0                   
  [9] BiocParallel_1.28.3           XGR_1.1.8                    
 [11] munsell_0.5.0                 DT_0.22                      
 [13] colorspace_2.0-3              OrganismDbi_1.36.0           
 [15] Biobase_2.54.0                filelock_1.0.2               
 [17] MACSr_1.2.0                   knitr_1.38                   
 [19] supraHex_1.32.0               rstudioapi_0.13              
 [21] DescTools_0.99.44             MatrixGenerics_1.6.0         
 [23] GenomeInfoDbData_1.2.7        bit64_4.0.5                  
 [25] echoconda_0.99.5              rprojroot_2.0.2              
 [27] basilisk_1.6.0                vctrs_0.4.0                  
 [29] generics_0.1.2                xfun_0.30                    
 [31] biovizBase_1.42.0             BiocFileCache_2.2.1          
 [33] R6_2.5.1                      AnnotationFilter_1.18.0      
 [35] bitops_1.0-7                  cachem_1.0.6                 
 [37] reshape_0.8.8                 DelayedArray_0.20.0          
 [39] assertthat_0.2.1              promises_1.2.0.1             
 [41] BiocIO_1.4.0                  scales_1.1.1                 
 [43] nnet_7.3-17                   rootSolve_1.8.2.3            
 [45] gtable_0.3.0                  lmom_2.8                     
 [47] ggbio_1.42.0                  ensembldb_2.18.4             
 [49] rlang_1.0.2                   clisymbols_1.2.0             
 [51] MungeSumstats_1.3.16          echodata_0.99.7              
 [53] splines_4.1.0                 lazyeval_0.2.2               
 [55] GEOquery_2.62.2               gargle_1.2.0                 
 [57] dichromat_2.0-0               hexbin_1.28.2                
 [59] checkmate_2.0.0               BiocManager_1.30.16          
 [61] yaml_2.3.5                    reshape2_1.4.4               
 [63] GenomicFeatures_1.46.5        ggnetwork_0.5.10             
 [65] backports_1.4.1               httpuv_1.6.5                 
 [67] Hmisc_4.6-0                   RBGL_1.70.0                  
 [69] tools_4.1.0                   ggplot2_3.3.5                
 [71] ellipsis_0.3.2                RColorBrewer_1.1-2           
 [73] proxy_0.4-26                  Rcpp_1.0.8.3                 
 [75] plyr_1.8.7                    base64enc_0.1-3              
 [77] progress_1.2.2                zlibbioc_1.40.0              
 [79] purrr_0.3.4                   RCurl_1.98-1.6               
 [81] basilisk.utils_1.6.0          prettyunits_1.1.1            
 [83] rpart_4.1.16                  SummarizedExperiment_1.24.0  
 [85] ggrepel_0.9.1                 cluster_2.1.3                
 [87] here_1.0.1                    fs_1.5.2                     
 [89] crul_1.2.0                    magrittr_2.0.3               
 [91] data.table_1.14.2             echotabix_0.99.5             
 [93] dnet_1.1.7                    openxlsx_4.2.5               
 [95] gh_1.3.0                      mvtnorm_1.1-3                
 [97] ProtGenerics_1.26.0           matrixStats_0.61.0           
 [99] xtable_1.8-4                  mime_0.12                    
[101] patchwork_1.1.1               hms_1.1.1                    
[103] XML_3.99-0.9                  jpeg_0.1-9                   
[105] gridExtra_2.3                 testthat_3.1.3               
[107] compiler_4.1.0                biomaRt_2.50.3               
[109] tibble_3.1.6                  crayon_1.5.1                 
[111] R.oo_1.24.0                   htmltools_0.5.2              
[113] later_1.3.0                   echoannot_0.99.4             
[115] tzdb_0.3.0                    Formula_1.2-4                
[117] tidyr_1.2.0                   expm_0.999-6                 
[119] Exact_3.1                     lubridate_1.8.0              
[121] DBI_1.1.2                     ExperimentHub_2.2.1          
[123] dbplyr_2.1.1                  MASS_7.3-56                  
[125] rappdirs_0.3.3                boot_1.3-28                  
[127] Matrix_1.4-1                  readr_2.1.2                  
[129] brio_1.1.3                    piggyback_0.1.1              
[131] cli_3.2.0                     R.methodsS3_1.8.1            
[133] parallel_4.1.0                igraph_1.2.11                
[135] pkgconfig_2.0.3               dir.expiry_1.2.0             
[137] GenomicAlignments_1.30.0      RCircos_1.2.2                
[139] foreign_0.8-82                osfr_0.2.8                   
[141] xml2_1.3.3                    stringr_1.4.0                
[143] VariantAnnotation_1.40.0      digest_0.6.29                
[145] graph_1.72.0                  httpcode_0.3.0               
[147] htmlTable_2.4.0               gld_2.6.4                    
[149] restfulr_0.0.13               curl_4.3.2                   
[151] shiny_1.7.1                   Rsamtools_2.10.0             
[153] rjson_0.2.21                  lifecycle_1.0.1              
[155] nlme_3.1-157                  jsonlite_1.8.0               
[157] limma_3.50.1                  fansi_1.0.3                  
[159] pillar_1.7.0                  lattice_0.20-45              
[161] GGally_2.1.2                  KEGGREST_1.34.0              
[163] fastmap_1.1.0                 httr_1.4.2                   
[165] survival_3.3-1                googleAuthR_2.0.0            
[167] waldo_0.4.0                   interactiveDisplayBase_1.32.0
[169] glue_1.6.2                    zip_2.2.0                    
[171] png_0.1-7                     BiocVersion_3.14.0           
[173] bit_4.0.4                     Rgraphviz_2.38.0             
[175] class_7.3-20                  stringi_1.7.6                
[177] blob_1.2.2                    AnnotationHub_3.2.2          
[179] latticeExtra_0.6-29           memoise_2.0.1                
[181] dplyr_1.0.8                   e1071_1.7-9                  
[183] ape_5.6-2     
```

</details>

**Comment by bschilder** [comment]
Possibly of interest to `regioneR` maintainer as well: @bernatgel

**Comment by hpages** [comment]
> The following produces an error when running it **from within a one of my package's functions (but, oddly, not when I run it line-by-line)**

That is a major clue to your problem here. Errors that occur from _within_ your package but not when running the code as _standalone_ code (like it's the case here) are _almost always_ caused by namespace issues in your package. In your case it's probably because you're not importing the `%in%` or `match()` generic functions from **BiocGenerics**.

Make sure you have:

    importFrom(BiocGenerics, "%in%", match)

in your `NAMESPACE`. Alternatively you can fully import **BiocGenerics** (which I strongly recommend since keeping track of what needs to be exported exactly can be tricky and error prone):

    import(BiocGenerics)

H.

**Comment by bschilder** [comment]
Hi @hpages , thanks for the quick reply. Yeah, it's definitely a namespace issue. 

I guess the part I'm unclear about is why the default version of `%in%` in R would work ok on its own (without declaring anything) but as soon as `BiocGenerics` is attached, an error is produced unless some additional care is taken to import the `BiocGenerics` version. This might simply be a blindspot in my understanding of namespaces.

Thanks, 
Brian

**Comment by hpages** [comment]
I'm not sure I fully understand the question and you're not providing code that allows me to reproduce the problem you are describing, plus I don't know what your package is, so I can't really help sorry.

H.

**Comment by bschilder** [comment]
Sorry if I wasn't very clear.
What I mean is, I normally use `%in%` (the default version of the function that is automatically available in base R ) to subset `GRanges` objects without an issue, and without importing its parent package `S4Vectors` in my functions' roxygen notes.

The `error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments` error only comes about when `BiocGenerics` is attached before attempting to subset a `GRanges` object with `%in%`(when implemented within a package function).

## Expected behaviour

I'd expect that even if `BiocGenerics::%in%` wasn't explicitly imported, the default version of `%in%` from base R would still be able to carry out the function without an error (as it does when running code line-by-line, or when `BiocGenerics` is not attached prior). Instead, it seems that attaching `BiocGenerics` to the namespace without explicitly importing it causes an error.

## Links

[Package function](https://github.com/RajLabMSSM/echoannot/blob/46d40ce5f5a108e2ef0dd1231dab6dbc888c3474/R/import_bedgraph_chroms.R) in question.
[Package](https://github.com/RajLabMSSM/echoannot) (installation instructions in readme).

## Reprex2

Using the version of `echoannot` with `%in%`:

```R
remotes::install_github("RajLabMSSM/echoannot@22edbdc")

 ids <- "GSM945244"
 query_granges <- GenomicRanges::GRanges("chr6:165169213-167169213")
 grl <- echoannot::import_peaks(ids = ids,
                                   builds = "hg19",
                                   query_granges = query_granges, 
                                   query_granges_build = "hg38")
```

Hope that helps a bit.

**Comment by hpages** [comment]
I'm still not able to reproduce the error you are describing, sorry:
```
remotes::install_github("RajLabMSSM/echoannot@22edbdc")
# ... lots of output

ids <- "GSM945244"
query_granges <- GenomicRanges::GRanges("chr6:165169213-167169213")
grl <- echoannot::import_peaks(ids = ids, builds = "hg19", query_granges = query_granges,  query_granges_build = "hg38")
# Setting options('download.file.method.GEOquery'='auto')
# Setting options('GEOquery.inmemory.gpl'=FALSE)
# Registered S3 method overwritten by 'GGally':
#   method from   
#   +.gg   ggplot2
# Querying 1 samples.
# 
# Query: GSM945244 
# Using build: hg19
# Determining available file types.
# 6 supplementary file(s) found: 
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdHotspotsRep1.broadPeak.gz
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdHotspotsRep2.broadPeak.gz
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdPkRep1.narrowPeak.gz
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdPkRep2.narrowPeak.gz
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdRawRep1.bigWig
#  - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdRawRep2.bigWig
# Using pre-computed narrowPeak files.
# scan() expected 'an integer', got '5034hr1'Saving results ==>  /tmp/RtmpgLKb9r/file14a9d3195cfd4grl.hg38.rds

grl
# GSM945244 
#        NA 
```
No problem!

Attaching **BiocGenerics** to the search path:
```
library(BiocGenerics)
grl <- echoannot::import_peaks(ids = ids, builds = "hg19", query_granges = query_granges,  query_granges_build = "hg38")
# same output as above

grl
# GSM945244 
#        NA 
```
Still no problem!

H.

**Comment by bschilder** [comment]
Actually, `NA` is the default output when an error is encountered (there's a `tryCatch` built in). Oddly, I'm seeing a different error message in your output though:
`scan() expected 'an integer', got '5034hr1`


I should mention, I haven't observed errors when attaching `library(BiocGenerics)` when manually running examples in the R console. It only occurs when `BiocGenerics` is attached inside a package, as it is when `regioneR::getGenome(genome ="hg19")` is invoked.

For reference, the output looks like this when I replace `%in%` with the `grepl` temporary solution I posted above:
![Screenshot 2022-03-31 at 19 05 42](https://user-images.githubusercontent.com/34280215/161121303-3f396ff4-5b52-433d-a561-be77f61416b8.png)

**Comment by hpages** [comment]
Why use `tryCatch()` in your code? Unless you have a very good reason to do so, it is generally a bad idea. Then you silently get wrong results.

Errata: after attaching **BiocGenerics**, I actually get a different result, but still no error:
```
> grl <- echoannot::import_peaks(ids = ids, builds = "hg19", query_granges = query_granges,  query_granges_build = "hg38")
Querying 1 samples.

Query: GSM945244 
Using build: hg19
Determining available file types.
Using locally cached version of GSM945244 found here:
/tmp/RtmpDMw2G2/GSM945244.soft 
6 supplementary file(s) found: 
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdHotspotsRep1.broadPeak.gz
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdHotspotsRep2.broadPeak.gz
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdPkRep1.narrowPeak.gz
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdPkRep2.narrowPeak.gz
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdRawRep1.bigWig
 - GSM945244_hg19_wgEncodeUwHistoneA549H3k04me3StdRawRep2.bigWig
Using pre-computed narrowPeak files.
Performing liftover:  hg19  ==>  hg38
Downloading chain file from UCSC Genome Browser.
trying URL 'ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz'
Content type 'unknown' length 227698 bytes (222 KB)
==================================================
/home/hpages/.cache/R/echotabix/hg19ToHg38.over.chain.gz
Subsetting peaks.
Saving results ==>  /tmp/RtmpDMw2G2/file156955c3442e4grl.hg38.rds

> grl
$GSM945244
GRanges object with 98 ranges and 8 metadata columns:
                       seqnames              ranges strand |        name
                          <Rle>           <IRanges>  <Rle> | <character>
  supplementary_file_3     chr6 165309312-165309461      * |        <NA>
  supplementary_file_3     chr6 165552493-165552642      * |        <NA>
  supplementary_file_3     chr6 165556713-165556862      * |        <NA>
  supplementary_file_3     chr6 165630953-165631102      * |        <NA>
  supplementary_file_3     chr6 165660273-165660422      * |        <NA>
                   ...      ...                 ...    ... .         ...
  supplementary_file_4     chr6 166382673-166382822      * |        <NA>
  supplementary_file_4     chr6 166383353-166383502      * |        <NA>
  supplementary_file_4     chr6 166383633-166383782      * |        <NA>
  supplementary_file_4     chr6 166626753-166626902      * |        <NA>
  supplementary_file_4     chr6 166627953-166628102      * |        <NA>
                           score signalValue    pValue    qValue      peak
                       <numeric>   <numeric> <numeric> <numeric> <integer>
  supplementary_file_3         0          37  64.75870        -1        -1
  supplementary_file_3         0          11  12.84560        -1        -1
  supplementary_file_3         0           8   5.21141        -1        -1
  supplementary_file_3         0           8   6.67611        -1        -1
  supplementary_file_3         0          18  25.01350        -1        -1
                   ...       ...         ...       ...       ...       ...
  supplementary_file_4         0          40   64.7896        -1        -1
  supplementary_file_4         0          54  122.3850        -1        -1
  supplementary_file_4         0          73  122.3850        -1        -1
  supplementary_file_4         0          13   11.3143        -1        -1
  supplementary_file_4         0          41   64.7896        -1        -1
                                       source peakwidth
                                  <character> <integer>
  supplementary_file_3 GSM945244_hg19_wgEnc..       150
  supplementary_file_3 GSM945244_hg19_wgEnc..       150
  supplementary_file_3 GSM945244_hg19_wgEnc..       150
  supplementary_file_3 GSM945244_hg19_wgEnc..       150
  supplementary_file_3 GSM945244_hg19_wgEnc..       150
                   ...                    ...       ...
  supplementary_file_4 GSM945244_hg19_wgEnc..       150
  supplementary_file_4 GSM945244_hg19_wgEnc..       150
  supplementary_file_4 GSM945244_hg19_wgEnc..       150
  supplementary_file_4 GSM945244_hg19_wgEnc..       150
  supplementary_file_4 GSM945244_hg19_wgEnc..       150
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

Anyways, the fact that we get different results whether **BiocGenerics** is attached or not also strongly suggests a namespace issue.

base::`%in%` is _not_ a generic function so won't be able to dispatch on the correct method. You really need to call the `%in%` generic defined in **BiocGenerics** for that. This is why you need to import **BiocGenerics**.

H.

**Comment by bschilder** [comment]
> Why use tryCatch() in your code? Unless you have a very good reason to do so, it is generally a bad idea. Then you silently get wrong results.

Sure, it's a good idea to not use `tryCatch` whenever possible. But it's necessary in this case because the goal of the function is to import peak files from GEO. As I'm sure you've experienced, GEO supplementary files are not provided in a standardized format. I've tried to account for a variety of these scenarios, but unfortunately it's not possible to account for every single variation. Thus `tryCatch` helps the function to continue gathering as many peak files as possible while not getting hung up on outlier formats.

> base::%in% is not a generic function so won't be able to dispatch on the correct method.  

Not quite sure about this; if you try this you'll see it's defined in `base`. Notice the backticks when referencing functions with `%`:

```R
?base::`%in%` 
```

From the docs:

![Screenshot 2022-03-31 at 19 17 53](https://user-images.githubusercontent.com/34280215/161123186-c3ec049e-13cc-41c3-9483-d36ee0e48c08.png)

> You really need to call the %in% generic defined in BiocGenerics for that. This is why you need to import BiocGenerics.

I suppose my concern with this suggestion is that I'd be propagating the same issue I'm experiencing to other users who want to use `echoannot`'s functions in their own packages. Wouldn't want them to have to submit another GitHub Issue each time someone tries to import these functions, or other functions that happen to attach `BiocGenerics`.

**Comment by hpages** [comment]
Of course base::`%in%` is defined in base. But that doesn't make it a generic function does it? Let alone an S4 generic function!

 
To be even clearer on this and to circle back to your original question:

> why the default version of %in% in R would work ok on its own (without declaring anything) but as soon as BiocGenerics is attached, an error is produced

It's the other way around. The default version of `%in%` doesn't know how to handle Rle objects:
```
> library(S4Vectors)
> x <- Rle(11:8)
> base::`%in%`(x, 10:15)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```
But the `%in%` _generic_ function in **BiocGenerics** does:
```
> BiocGenerics::`%in%`(x, 10:15)
logical-Rle of length 4 with 2 runs
  Lengths:     2     2
  Values :  TRUE FALSE
```

> I suppose my concern with this suggestion is that I'd be propagating the same issue I'm experiencing to other users who want to use echoannot's functions in their own packages.

Nope. It's the opposite. By importing **BiocGenerics** the code in your package will be guaranteed to work, whatever your users do, and whatever other developers do in their own package. If you don't, you are at the mercy of what they'll do and you absolutely want to avoid that :wink: 
 
H.

**Comment by bschilder** [comment]
> Of course base::%in% is defined in base. But that doesn't make it a generic function does it? Let alone an S4 generic function!

Ah, I see what you mean. Apologies, I think I have misinterpreted the original sentence. 

> Nope. It's the opposite. By importing BiocGenerics the code in your package will be guaranteed to work, whatever your users do, and whatever other developers do in their own package. If you don't, you are at the mercy of what they'll do and you absolutely want to avoid that 😉

I see, that makes quite a bit of sense. 

Thank you so much for taking the time to explain all this. As you can tell, this is getting into the fringe of my knowledge on how packages work. Hopefully it will benefit anyone else who might have some confusion around this as well.

Best, 
Brian

**Comment by bernatgel** [comment]
Hi! 

@bschilder, thanks for adding me to this issue.

Just a quick question: 

@hpages, if I was to add the BiocGenerics import to regioneR itself, would this problem disappear for this case and others using regioneR inside of packages? And even if this is not the case, if BiocGenerics is attached when loading regioneR including the import would be a good idea anyway, right?

Thanks!

Bernat

**Comment by hpages** [comment]
@bernatgel 

> if I was to add the BiocGenerics import to regioneR itself, would this problem disappear for this case and others using regioneR inside of packages?

I'm not sure if by _this_ problem you mean the problem discussed above which is a problem with the **echoannot** package imports that breaks the `echoannot::import_peaks()` function. As explained above the only proper way to fix this problem is by explicitly importing **BiocGenerics** _in **echoannot**_. Importing **BiocGenerics** _in **regioneR**_ won't fix a function defined in another package.

In other words, you import **BiocGenerics** if your own code needs it, not if someone's else code does.

> And even if this is not the case, if BiocGenerics is attached when loading regioneR including the import would be a good idea anyway, right?

Not necessarily. Only import **BiocGenerics** in your package if your code needs it. I've not looked at **regioneR** so I don't know if it needs to import **BiocGenerics**.

That being said, most packages that use the **S4Vectors**/**IRanges**/**GenomicRanges**/**SummarizedExperiment**/**Biostrings** infrastructure need to be able to call various generic functions defined in **BiocGenerics**. They don't necessarily do it or know about it, and their code might still work (or at least seem to work) but it's only by chance. That's why it's important to get your imports right: you don't want to leave anything to chance!

H.

**Comment by bernatgel** [comment]
Ok! I definitely use GenomicRanges  and Biostrings in regioneR! And I'm pretty sure I use functions defined in BiocGenerics.

Thanks for the clear explanations, @hpages! Helpful as always :)
