### ISSUE TITLE
Add dplyr to BiocGenerics's Depends field

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocGenerics#20]
### Proposal

Add **dplyr** to **BiocGenerics**'s `Depends` field.

#### The problem

We have currently 31 software packages in Bioconductor that put **dplyr** on the `search()` path, either intentionally by having it in `Depends`, or unintentionally by depending (directly or indirectly) on a package that has it in `Depends`. See at the end of this post for the full list.

This masks some of the S4 generics defined in **BiocGenerics**, like `combine()`, `intersect()`, `setdiff()`, `union()`, and therefore breaks things like:
- `combine(data.frame(aa=11:13), data.frame(bb=21:24))` if any of these 31 packages gets loaded after **BiocGenerics**;
- `intersect(IRanges("11-20"), IRanges("15-30"))` if any of these 31 packages gets loaded after **IRanges**.

More generally, any package that implements an S4 method for one of the above generics will break if any of these 31 packages is loaded after it.

For the anecdote, we've found at least one package that manages to put **dplyr** on the `search()` path without having it in `Depends` (and without depending on a package that has it in `Depends`): **tidySummarizedExperiment**. It does so by calling an internal function (`tidySummarizedExperiment::tidyverse_attach()`) in its `.onAttach()` hook to explicitly put **dplyr** (and other packages) on the search path. The result is the same as with any of the 31 packages mentioned abov, that is, loading it will also break the `combine()` and `intersect()` methods defined in other packages.

Sure, the user can work around this by using `BiocGenerics::combine()` or `BiocGenerics::intersect()`, but:
- few users would know what to do;
- it can be a real annoyance to have to use this in an interactive session.

So not really a satisfying answer to the problem.

#### Why is it a problem only now?

There's a growing interest in bringing more tidy functionality in Bioconductor with more and more tidyxxx and dplyxxx package submissions to Bioconductor. All these packages depend (via `Depends` or `Imports`) on **dplyr** for its popular verbs (`mutate`, `select`, `filter`, etc...). As more tidyxxx/dplyxxx packages make it into Bioconductor, the more frequent name clashing events are going to be.
 
#### The proposed solution

One way to solve this problem once for all -- and to greatly improve the user experience -- is to have **BiocGenerics** depend on **dplyr** (via `Depends`). That way the former would always be in front of the latter in the `search()` path. Additionally this will give us the opportunity to turn some popular **dplyr** verbs llike `mutate()`, `select()`, `filter()`, etc... into S4 generics in **BiocGenerics** if that's something that the authors of the tidyxxx and plyxxx packages in Bioconductor think they could benefit from.

Note that we've created **BiocGenerics** many years ago with the precise goal to fight name conflicts, and it's been a very effective way of doing that. This proposal is the continuation of this on-going effort, but with the difference that it would be the first time that **BiocGenerics** depends on a package that is not part of base R. 

However IMO this is a minor concern. Here's why:
1. Even though **dplyr** itself depends on 15 packages (not counting base packages), all of them are pretty small. The total size of the 16 source tarballs (**dplyr** + its 15 deps) is only 5.9M.
2. Installing these 16 packages from source is pretty fast: it takes less than a minute to download/install/compile them on an average Linux laptop. Hey, **dplyr** is NOT **duckdb**! :wink: (Of course users who install binary packages -- e.g. Windows and Mac users -- don't care about compilation times.)
3. `library(dplyr)` only adds 1 package to the `search()` path.
4. In fact, **dplyr** is already _imported_ (directly or indirectly) by hundreds of Bioconductor packages, so 99.9% (made up number!) of Bioconductor users already have it installed. Therefore 1. and 2. above would only matter for the 0.1% of Bioconductor users who don't already have **dplyr** on their machine.

It's also worth noting that having **BiocGenerics** depend on **dplyr** will put the latter at the far end of the `search()` path in the typical Bioconductor session. This will provide additional protection against potential additions to the **dplyr** vocabulary by the **dplyr** developers because none of these additions will be able to mask a Bioconductor verb.

#### Alternative solution (added on Oct 27)

An alternative would be to add **generics** instead of **dplyr** to **BiocGenerics**'s `Depends` field. **generics** is a thin tidyverse package that defines a bunch of S3 generics that are relevant to the tidyverse like `intersect()`, `setdiff()`, `setequal()`,  `union()`, etc... **dplyr** depends on it (via `Imports`). You could say that it's to the tidyverse what **BiocGenerics** is to Bioconductor, kind of, but with the important difference that the former defines S3 generics and the latter S4 generics.

If we add **generics** to **BiocGenerics**'s `Depends` field, and change the definition of the default S4 methods for `intersect()`, `setdiff()`, and `union()` to call `generics::intersect()`, `generics::setdiff()`, and `generics::union()` instead of `base::intersect()`, `base::setdiff()`, and `base::union()`, like they do at the moment, then we would solve the masking situation with **dplyr**. BUT THAT WORKS ONLY IF THE **dplyr** FOLKS MAKE THE FOLLOWING CHANGES TO THEIR PACKAGE:
1. Move **generics** from `Imports` to `Depends`.
2. I _think_ they would also need to stop reexporting `intersect()`, `setdiff()`, and `union()` (not sure about that, I need to investigate a little bit more).

**generics** is a _very very light_ package with no dependencies and no native code.

This solution would be cleaner than the above proposed solution but it requires that the **dplyr** folks are willing to make a couple small changes to their package.

### Comments welcome

Please note that this is not the place to debate about tidyverse syntax vs "traditional" syntax, or about which one is your favorite. Let's keep the discussion focused on name clashes in Bioconductor and how to avoid them. This proposal is an easy way to achieve that for the **dplyr** verbs, and to make the tidyverse and "traditional" syntax coexist peacefully in the ecosystem.

### List of Bioconductor software packages that put **dplyr** on the `search()` path  (as of Oct 25, 2024)

AlphaMissenseR, AMARETTO, AnVIL, bioCancer, BiocSet, broadSeq, BubbleTree, canceR, cBioPortalData, cellxgenedp, ceRNAnetsim, DFplyr, GNOSIS, Guitar, HiCcompare, IsoformSwitchAnalyzeR, octad, omada, optimalFlow, Organism.dplyr, pfamAnalyzeR, protGear, QuaternaryProd, RegEnrich, Rtpca, tidyomics, tidySingleCellExperiment, tidySpatialExperiment, tidySummarizedExperiment, TPP, TPP2D

How this list was obtained:
<details>
  <summary>see details</summary>

1. Clone the BioC manifest repo:
    ```
    git clone https://git.bioconductor.org/admin/manifest.git
    ```
6. Put the following code in `put_dplyr_on_search_path.R`:
    ```
    are_you_putting_me_on_the_search_path <- function(you, me, verbose=FALSE)
    {
        if (isTRUE(verbose))
            message("Checking ", you, " ... ", appendLF=FALSE)
        Rscript <- file.path(R.home("bin"), "Rscript")
        fmt <- "suppressMessages(library(%s));cat(\"package:%s\"%%in%%search())"
        Rexpr <- sprintf(fmt, you, me)
        out <- suppressWarnings(
            system2(Rscript, c("-e", paste0("'", Rexpr, "'")), stdout=TRUE)
        )
        if (isTRUE(verbose))
            message("OK")
        status <- attr(out, "status")
        if (!is.null(status) && status != 0)
            return(NA)
        identical(out, "TRUE")
    }
    
    ## Check all software packages in BioC 3.21 (all of them need to be installed):
    manifest <- "path/to/manifest/software.txt"
    softpkgs <- read.table(manifest)[[2]]
    
    length(softpkgs)  # 2281 software packages in BioC 3.21 on Oct 25, 2024
    
    ## Takes about 3-4 hours on a Linux machine that has (almost) all the software
    ## packages installed:
    system.time(yes <- sapply(softpkgs, are_you_putting_me_on_the_search_path, "dplyr", TRUE))
    
    saveRDS(yes, "put_dplyr_on_search_path.rds")
    
    table(yes, useNA="ifany")
    ```
7. Adjust `manifest`.
8. Run script with `path/to/R/bin/Rscript put_dplyr_on_search_path.R >put_dplyr_on_search_path.log 2>&1 &`
</details>

**Comment by mtmorgan** [comment]
`dplyr::filter()` and `stats::filter()` are not compatible; the change breaks scripts using base R functionality.

dplyr exports ~300 symbols, conflicting with use in other packages. Is there an alternative that addresses the most important verbs?

**Comment by LTLA** [comment]
A dependency at install/load time must still be considered as a maintenance burden. What if **dplyr** or any of its dependencies decides to, e.g., set a `SystemRequirements` of C++20? Then we would be locked out of installing BiocGenerics on older systems without C++20 support. **dplyr** and many of its dependencies also do something in their `.onLoad()`, which is another potential source of problems on package load, even if **dplyr** functions are never used.

You previously mentioned that a developer shouldn't worry about indirect dependencies. But I must, because that ultimately affects the user experience for my package. For example, I watched with concern as new packages started creeping into my `sessionInfo()` throughout the past few release cycles. I was fine with those that just involved shuffling existing code from **DelayedArray** (e.g., **S4Array**, **SparseArray**) - no real harm done there, and besides, they're all BioC packages so any changes won't break release. I was considerably more alarmed when **httr** became a dependency of **GenomeInfoDb** via the new **UCSC.utils** package - I didn't recall that being there before. This adds all of *httr*'s indirect `SystemRequirements` (e.g., libcurl, OpenSSL) to our dependencies, increasing the surface area of potential issues. Indeed, a few years ago, we were told to prefer GnuTLS instead of OpenSSL in our R installs - some license issue, perhaps, and I don't recall how we managed to worm out of that to get the **openssl** R package installed.

To me, the benefits of avoiding masking for a non-base package do not justify the cost of the extra dependencies. I also think it sets a dangerous precedent in that users of other popular packages (e.g., **data.table**) could ask us to accommodate them. If a better technical solution (i.e., one that does not rely on **dplyr** installation) cannot be found, I would be perfectly satisfied with telling these "tidyverse + BioC" users to just namespace their calls via `::`. This is standard practice in most other programming languages, and outside of the tidyverse doctrine, verbosity is not a crime.

**Comment by kuwisdelu** [comment]
I agree with the general motivation to provide a centralized source of __tidyverse__ generics for Bioconductor packages. But adding __dplyr__ to the search path is worrying. As others have pointed out, even if we never explicitly depend on __dplyr__ in our own packages, it adds a burden when considering potential namespace conflicts.

I still think there can be a more elegant technical solution that involves a separate __TidyGenerics__ package for the packages that want it. I know the challenge is that doesn’t solve the issue of `BiocGenerics::intersect`, `BiocGenerics::combine`, etc., getting masked on the search path.

But could we consider moving the conflicting generics *out* of __BiocGenerics__ and *into* a __TidyGenerics__ package that separately depends on __dplyr__? I know that would cause more headache in the short term as the packages using them would need to add a __TidyGenerics__ dependency. But I think it would be significantly better in the long term.

Because then maintainers could decide whether we want both dependencies or not. It would be helpful at least to consider how many and which generics would be affected by such a change. If we needed `BiocGenerics::combine` before, we could switch to `TidyGenerics::combine`. The only technical downside to this would be if someone needed those specific generics but really didn’t want the `dplyr` dependency.

**Comment by eddelbuettel** [comment]
Why not fix the 31 packages with simple PRs that make the namespace use explicit?

**Comment by hpages** [comment]
Another solution would be to add **generics** instead of **dplyr** to **BiocGenerics**'s `Depends` field, but it comes with a catch. See **Alternative solution (added on Oct 27)** in my initial post above for the details (I just edited it).

Any thoughts on that one?

**Comment by kuwisdelu** [comment]
Personally, I'm fully supportive of using a **generics** dependency for this if the tidyverse devs are willing.

(Personally, I always wondered why those generics were in **dplyr** instead of **generics** in the first place.)

**Comment by LTLA** [comment]
Seems like a good compromise to me, though let's see what the **dplyr** folks say before we get too excited.

**Comment by aitap** [comment]
If you're only concerned with `dplyr`, I think that `BiocGenerics` could use [setHook](https://search.r-project.org/R/refmans/base/html/userhooks.html) to have itself reattached above `dplyr` any time the latter is attached by `attachNamespace` (i.e. by `library` or `require`). This will not create a strong dependency (maybe `Enhances:`?) and should cover both user calls to `library`/`require` and `tidySummarizedExperiment:::tidyverse_attach` because the latter uses `library`:

```r
# in BiocGenerics:::.onLoad:
setHook(packageEvent('dplyr', 'attach'), \(...) {
 # attachNamespace takes care that a package is attached no more than once
 pos_BiocGenerics <- which(search() == 'package:BiocGenerics')
 if (!length(pos_BiocGenerics)) return() # not already attached - no problem

 pos_dplyr <- which(search() == 'package:dplyr')
 if (
  !length(pos_dplyr) || # should never happen - the hook is run after package:dplyr is attached
  pos_dplyr > pos_BiocGenerics # already behind BiocGenerics
 ) return()

 detach('package:BiocGenerics', force = TRUE)
 attachNamespace('BiocGenerics', pos = pos_dplyr) # shifting dplyr right
})
```

If the idea is to eventually generalise the rule to "BiocGenerics are never shadowed" and have it work automatically, an approach similar to the one in the [`conflicted`](https://cran.r-project.org/package=conflicted) CRAN package might work. (Except `conflicted` works by attaching an environment shadowing `base::library`, so may not work for package calls to `library` - not sure - or explicit calls to `base::library`.)

**Comment by Shians** [comment]
I think Martin's concern must be addressed before thinking about anything else. At a minimum the solution must be such that:

1. Both BioC and dplyr works as before, if someone has dplyr loaded after BioC in a script, expecting the masking and coding accordingly, then it must work as before.
2. It can't break any base code by adding dplyr verbs through the dependency to scripts that previously didn't have them. If someone's script loaded in BioC packages that previously didn't have any `dplyr` loaded, conflicts like `stats::filter()` must resolve in favor of `stats::filter()`. Fortunately It think it's only `stats::lag()` and `stats::filter()` that have this issue.

I agree that most people already have `dplyr` installed, and that it's unlikely to result in any additional maintenance burden. I don't think there are many people making use of BioC packages without having acquired `dplyr` somehow.

I don't think it's productive to speculate about changes `dplyr` could make that would substantially impact the BioC ecosystem, this proposal isn't a tight coupling to `dplyr` anyway. If anything does happen I don't think it'll be that hard to go back to the way things were and make people namespace everything themselves. A quick glance at the `dplyr` reverse depends and imports tells me there would be very substantial inertia preventing serious breaking changes.

If creating the dependency and defining the generics allow both namespaces to be called correctly for their contexts without additional burden on the user and without breaking existing code, then I am all for these changes.

**Comment by LTLA** [comment]
> I don't think it's productive to speculate about changes `dplyr` could make that would substantially impact the BioC ecosystem

Well, introducing any dependency requires one to think about the risks involved in doing so. Most of my maintenance problems over the past decade have involved changes made by some dependency. Ignoring this new source of fragility would be irresponsible.

> If anything does happen I don't think it'll be that hard to go back to the way things were and make people namespace everything themselves.

Once you make this kind of compatibility promise, breaking it is worse than not making it in the first place.

> A quick glance at the `dplyr` reverse depends and imports tells me there would be very substantial inertia preventing serious breaking changes.

That is an optimistic perspective.

**Comment by hpages** [comment]
@mtmorgan @shians Yes `dplyr::filter()` masking and breaking `stats::filter()` is not good. But we also have at least one popular package in Bioconductor that masks and breaks `stats::filter()`.  And of course the `filter()` functions in **dplyr** and in Bioconductor break each others :disappointed: Lots of bad practices around! Sadly, it looks like nobody cares about poor `stats::filter()` and feels entitled to step on it with their big boots :wink:

That being said, I'm not aware of anything in Bioconductor _at the moment_ that breaks because of `stats::filter()` being stepped on either by `dplyr::filter()` or by `ensembldbl::filter()`. Not trying to justify bad practices here. Only saying that, because I didn't see this masking as an imminent threat, I thought I would keep it for another discussion for another time, and would focus on the verbs in **BiocGenerics** that _I know_ are being stepped on, and break, when **dplyr** gets attached.

Finally note that:
1. The `filter()` function in **ensembldb** will break if **dplyr** gets loaded after **ensembldb**, which would actually be an argument _in favor_ of attaching **dplyr** _as early as possible_ to the user's session (this is what having **dplyr** in **BiocGenerics**'s `Depends` field would achieve).
2. If we take the **generics** route (see **Alternative solution** in my initial post for the details), then we can completely ignore the `filter()` story for now, because it becomes an orthogonal issue (there's no `filter()` in **generics** or in **BiocGenerics**).

**Comment by hpages** [comment]
> Why not fix the 31 packages with simple PRs that make the namespace use explicit?

@eddelbuettel Just to clarify, they work fine. They don't need a fix. But maybe you are suggesting that no package in Bioconductor should be allowed to have **dplyr** in `Depends`, only in `Imports`? So the "fix" in this case would be that Bioconductor packages that have  **dplyr** in `Depends` move it to `Imports`?

Yes this would probably help _reduce_ the risk of having **dplyr** randomly pop up on the user's `search()` path during a session, but it would not _eliminate_ it , unless all CRAN packages that are dependencies of Bioconductor packages do the same.

**Comment by Shians** [comment]
The generics solution sounds like a good route, and if we're in touch in `dplyr` devs anyway, we can also voice concerns about toolchain/dependency changes and whether it's likely to happen in the future. My impression is that `dplyr` is a mature stable package that is unlikely to change in any significant way in the future. The fraction of BioC users who would be unable/unwilling to install `dplyr` is very tiny.  Making these changes today seem to have properly considered and quite minor downsides, especially under the assumption almost everyone already has `dplyr` installed.

The question is whether `dplyr` makes some big changes that render it unusable/uninstallable to a significant portion of users in the future. I will optimistically say probably not.

**Comment by jonocarroll** [comment]
Having generics for the `dplyr` verbs in `generics` and then `BiocGenerics` would mean `DFplyr` would not need to depend on `dplyr` at all. I suspect the same would be true for some of the other packages providing dplyr-esque functionality on top of BioC structures, but at least those needing `dplyr` calls would not cause breakage.

**Comment by hpages** [comment]
Thanks @aitap for the `setHook()` suggestion. I'm a little bit nervous with this approach though because I'm not sure what the exact consequences of moving **BiocGenerics** to the beginning of the `search()` path could be, especially if this happens after many packages that depend on it are already attached. Now they're all going to be _after_ **BiocGenerics**, which is a very unnatural situation that no developer of any of these packages had in mind when they worked on their package.

More generally speaking it seems to me that playing the "let's shuffle the `search()` path game" introduces the potential for a  lot of unforeseen adverse consequences. Anyways, good to know that this option is available but I prefer to keep it as a last resort for now.

Note that there's also the option to automatically add **conflicted** to the user session (e.g. by making it a dep of **BiocGenerics**) and to let the end user disambiguate calls interactively when they are prompted by **conflicted**. Not a big fan of that one either.

**Comment by hpages** [comment]
**Alternative solution** implemented in **BiocGenerics** 0.53.1 (BioC 3.21, requires R 4.5): https://github.com/Bioconductor/BiocGenerics/commit/b18a5f2b74f506454eba15e8a229e12206f9e57f

The good news is that the **dplyr** folks don't need to do anything :smiley: :
```
library(IRanges)

intersect(IRanges("11-20"), IRanges("15-30"))
# IRanges object with 1 range and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]        15        20         6

library(dplyr)

intersect(IRanges("11-20"), IRanges("15-30"))  # breaks in BioC 3.20!
# IRanges object with 1 range and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]        15        20         6
```

Not many **dplyr** verbs are actually defined as S3 generics in the **generics** package, but we are just lucky here that the "setops verbs" (`intersect`, `union`, etc...) are. However, the good thing is that if other **dplyr** verbs turn out to clash with verbs in Bioconductor, we could always ask the tidyverse folks to put them in **generics** so we can use the same setup as with the "setops verbs" to avoid the clash. This kind of change is pretty straightforward and should not be disruptive.  

**sessionInfo()**
```
R Under development (unstable) (2024-10-22 r87265)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.5.r87265/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] dplyr_1.1.4         IRanges_2.41.0      S4Vectors_0.45.0   
[4] BiocGenerics_0.53.1 generics_0.1.3     

loaded via a namespace (and not attached):
 [1] utf8_1.2.4       R6_2.5.1         tidyselect_1.2.1 magrittr_2.0.3  
 [5] glue_1.8.0       tibble_3.2.1     pkgconfig_2.0.3  lifecycle_1.0.4 
 [9] cli_3.6.3        fansi_1.0.6      vctrs_0.6.5      compiler_4.5.0  
[13] pillar_1.9.0     rlang_1.1.4     
```

**Comment by ahl27** [comment]
Sorry I'm late to the party...I unfortunately happen to be one of the 0.1% Bioconductor users that don't have `dplyr` (or any tidyverse packages) installed. I think most of the main points I would've said have already been mentioned, but I just wanted to add some input from my end.

>  ...but with the difference that it would be the first time that BiocGenerics depends on a package that is not part of base R.

I think this is a pretty big deal. One of Bioconductor's strengths is regular release cycles, and adding a dependency to one of the most core Bioconductor packages that lives outside the standard Bioconductor release cycle opens things up to break spontaneously. I'm not sure it's a huge concern, but it's definitely something to be aware of. People have already mentioned that `dplyr` is a mature package that's unlikely to have those types of changes, but "unlikely to have breaking changes in dependencies" is a huge difference from "will not have breaking changes in dependencies".

My preference would be to go the `generics` route. It seems less likely to have major changes than `dplyr` and introduces a lot fewer dependencies. `dplyr` does install quickly, but I'm still not sure it warrants the added bloat (it's not much, but I do know of several people that really care about that sort of thing). It's also more inline with the package goals...the `generics` package's purpose seems to be specifically for generic name conflict resolution, whereas depending on all of `dplyr` seems like overkill. Also seems like it would involve less work coordinating with the tidyverse team.

The solution in https://github.com/Bioconductor/BiocGenerics/commit/b18a5f2b74f506454eba15e8a229e12206f9e57f looks like a very clean approach to resolve the problem.

**Comment by hpages** [comment]
@ahl27 Yup. I'm glad we have the ability to address name conflicts and keep everything nice and tidy thru the **BiocGenerics**/**generics** duo. I didn't realize this initially hence why I suggested to add **dplyr** to **BiocGenerics**'s `Depends` field. But in hindsight, the **BiocGenerics**/**generics** duo seems like the natural way to go.

Thanks to everybody for their feedback/comments.

I'll close this now.

**Comment by hpages** [comment]
> Having generics for the **dplyr** verbs in **generics** and then **BiocGenerics** would mean **DFplyr** would not need to depend on **dplyr** at all.

@jonocarroll Absolutely, this would be a cleaner setup. There are a lot of verbs in **dplyr** though, as @mtmorgan mentioned earlier, so I guess the focus would be on the small subset used by **DFplyr** and the other tidyxxx/dplyxxx packages in Bioconductor, at least as a starting point.

I suggest that you and the developers of the other tidyxxx/dplyxxx packages in Bioconductor team together to discuss this proposal with the **dplyr** folks. Is there a "tidy" working group in Bioconductor? Maybe there should be one. 

H.

**Comment by jonocarroll** [comment]
> I suggest that you and the developers of the other tidyxxx/dplyxxx packages in Bioconductor team together to discuss this proposal with the dplyr folks. 

@hpages I did find this issue https://github.com/r-lib/generics/issues/41 which makes me think that such an approach would not be welcomed, though I'd be happy to hear if that opinion has evolved.

> Is there a "tidy" working group in Bioconductor? Maybe there should be one.

I originally thought the tidyomics project might be leading towards this, but that's perhaps beyond their goals. Otherwise, the #tidiness_in_bioc in channel on the community-bioc slack seems like a place to continue that proposal.

**Comment by hpages** [comment]
> I did find this issue [r-lib/generics#41](https://github.com/r-lib/generics/issues/41) which makes me think that such an approach would not be welcomed, though I'd be happy to hear if that opinion has evolved.

@jonocarroll Ah, that is not very encouraging indeed! But the issue lacks context and is almost 6-year old so who knows.

> Otherwise, the #tidiness_in_bioc in channel on the community-bioc slack seems like a place to continue that proposal.

Good to know about this channel, was not aware. Thanks!

**Comment by llrs-roche** [comment]
Sorry to continue add to the discussion after it is closed but I don't see an answer to [Martin Morgan asking for alternatives](https://github.com/Bioconductor/BiocGenerics/issues/20#issuecomment-2439430676).

The R core thought about this problem and provided arguments in library to help reduce these conflicts. They are underused and could be promoted for instance by using them on vignettes: use mask.ok, include.only or exclude on `library()`.

From reference: https://blog.r-project.org/2019/03/19/managing-search-path-conflicts/index.html

It contains the relevant sentence : “In the future it might be worth considering whether this information could be encoded in a package’s DESCRIPTION file.” which would leave the conflctRules in hands of the developers. Maybe the R core members might be open to work on this if there is enough interest and a patch proposal from Bioconductor.

**Comment by llrs** [comment]
Sorry to continue add to the discussion after it is closed but I wanted to propose a different alternative.

The R core thought about this problem and provided arguments in library to help reduce these conflicts. They are underused and could be promoted for instance by using them on vignettes: use mask.ok, include.only or exclude on `library()`.

From reference: https://blog.r-project.org/2019/03/19/managing-search-path-conflicts/index.html

It contains the relevant sentence : “In the future it might be worth considering whether this information could be encoded in a package’s DESCRIPTION file.” which would leave the conflctRules in hands of the developers. Maybe the R core members might be open to work on this if there is enough interest and a patch proposal from Bioconductor.
