### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xuebaliang** [Bioconductor/BiocGenerics#4]
Hello, I have installed the BioGenerics of newest version 0.32 on my linux server. But when I import it, I get the following error,
> library(BiocGenerics)
Error in value[[3L]](cond) : 
  Package ‘BiocGenerics’ version 0.30.0 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘BiocGenerics’ is imported by ‘GenomicRanges’, ‘XVector’, ‘S4Vectors’, ‘GenomeInfoDb’, ‘IRanges’ so cannot be unloaded

How to fix this problem? Thanks.

**Comment by hpages** [comment]
Can we close this too?
