### ISSUE TITLE
No need to refer to scater::normalize anymore

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocGenerics#5]
I was wondering why **scater** and **SingleCellExperiment** had rev-suggests from **BiocGenerics**, but `scater::normalize` is now defunct so these are no longer relevant.

IMO this generic is far too... generic for a relatively complex analytical step, but what's done is done.

**Comment by hpages** [comment]
Done (commit 77ab03b27978848804c786aa4634522d7b7afb37). No more free advertising for you ;-)
