### ISSUE TITLE
R-devel 

### ISSUE THREAD

**Issue by kullrich** [Bioconductor/BiocGenerics#6]
Hi, since this commit (https://github.com/Bioconductor/BiocGenerics/commit/69e6fad3792d19383e0782ef7a3bf70658bb7159) it seems that the R-devel travis ci gives an warning if one uses the base `which` function and importing BiocGenerics.
See here for more information on it.

https://support.bioconductor.org/p/131811/

The warning is as follows:

Warning: multiple methods tables found for 'which'

Thank you in anticipation for sorting this out.

Best regards

Kristian Ullrich

**Comment by lshep** [comment]
Lets keep the conversation in one spot and reopen the issue if a bug is found. 

Continue conversation on your open support site issue: 
https://support.bioconductor.org/p/131811/

And the referenced: 
https://support.bioconductor.org/p/131689/
https://github.com/Bioconductor/BiocGenerics/issues/3
